[package]
name = "btreeset-throughput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-skiplist = "0.1.1"
crossbeam-utils = "0.8.16"
rand = "0.8.5"
